server:
  port: 8771



spring:
  application:
    name: order-server


#将order-service注册到注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


#自定义负载均衡策略.改为随机，默认是轮询的方式，
product-server:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


#配置feignclient调用超时时间，但由于hystrix默认超时时间是1s，所以要同时调整hystrix的超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

